matrix:
  include:
    - language: node_js
      node_js:
        - 14
      before_install:
        - cd LandingPage
      install:
        - npm install
      script:
        - npm run test:record
        - kill $(jobs -p) || true
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: LandingPage/build
        on:
          branch: dev/master
